config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'pages#index'
  get 'dokralex', to: 'pages#dokralex', as: 'dokralex'
  get 'hema_dalavayi', to: 'pages#hema_dalavayi' , as: 'hema_dalavayi'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def dokralex
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamCollab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/dokralex.html.erb
<h1>Hi, I'm Alex Do, username is DoKrAlex</h1>

<h2>Have a Bocchi</h2>

<%= image_tag "bocchi.png", size: "400x400" %>

app/views/pages/hema_dalavayi.html.erb
<h1> I am a CS Major with a concentration in Artificial Intelligence </h1>

app/views/pages/index.html.erb
<h1>Directory of Student Pages</h1>

<ul>
    <li><%= link_to 'DoKrAlex', dokralex_path %></li>
    <li><%= link_to 'hema_dalavayi', hema_dalavayi_path %></li>
</ul>

app/views/pages/username.html.erb
<h1>Hi, I'm Alex Do, username is DoKrAlex</h1>

<h2>Have a Bocchi</h2>

<%= image_tag "bocchi.png", size: "200x200" %>